language: rust
rust:
  - stable
  - beta
  - nightly
script:
  # test sequentially for environment tests
  - cargo build --all --verbose
  - cargo test --verbose -- --test-threads 1
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
